### ISSUE TITLE
Big Sur 可以用此EFI引导吗？

### ISSUE THREAD

**Issue by wqianglxf** [sbfkcel/Gigabyte-Z490i-Intel-10700k-5700XT#1]
我和您配置相同，才用来引导Bigsur![image](https://user-images.githubusercontent.com/66858128/106841285-ce01e100-66dc-11eb-95cb-ccbda79e4f7d.jpeg)

**Comment by sbfkcel** [comment]
理论上是可以的。你这个可能 USB 得自己定制一下，因特尔网卡兼容有点问题。

**Comment by wqianglxf** [comment]
是的，USB要重新订制，不然会卡AppleUSBXHCI。我的网卡是BCM943602CS，Bigsur不识别。商家让拆原装WiFi才能识别，您是通过什么方式禁用的？![image](https://user-images.githubusercontent.com/66858128/106867524-ac1e5380-6708-11eb-8de5-f2e221c2c1a6.jpeg)

**Comment by sbfkcel** [comment]
我是某宝上搞了块 MAC 支持的网卡。Intel 的无线驱动虽然有，但测试了，目前效果还不好。

**Comment by wqianglxf** [comment]
> 我是某宝上搞了块 MAC 支持的网卡。Intel 的无线驱动虽然有，但测试了，目前效果还不好。

我就是在某宝买的，但系统上只显示了intel的WiFi 蓝牙，似乎需要禁用后才能显BCM网卡

**Comment by sbfkcel** [comment]
把默认的 intel 网卡屏蔽掉再看看吧。

**Comment by wqianglxf** [comment]
嗯，搞定了。你后面还会更新吗

**Comment by sbfkcel** [comment]
> 嗯，搞定了。你后面还会更新吗

看具体情况了。有重大改进提升就更新。不会为追求新版本而更新。

**Comment by sbfkcel** [comment]
> 嗯，搞定了。你后面还会更新吗

看具体情况了。有重大改进或性能方面提升就更新。不会为追求新版本而更新。

**Comment by wqianglxf** [comment]
我的BCM943602CS，睡眠会自动唤醒。我重新定制了USB，内建和外置都不行。网卡的蓝牙我连接在主板的USB转接线，如果不连接就正常，这是什么原因呢？

**Comment by sbfkcel** [comment]
> 我的BCM943602CS，睡眠会自动唤醒。我重新定制了USB，内建和外置都不行。网卡的蓝牙我连接在主板的USB转接线，如果不连接就正常，这是什么原因呢？

看样子应该是定制的端口估计错了，先插拔确认下端口号。蓝牙只要 usb 2.0即可。另外启用的 USB 端口不要超过15个。

**Comment by sbfkcel** [comment]
> 我的BCM943602CS，睡眠会自动唤醒。我重新定制了USB，内建和外置都不行。网卡的蓝牙我连接在主板的USB转接线，如果不连接就正常，这是什么原因呢？

看样子应该是定制的端口估计错了，先插拔确认下端口号。蓝牙只要 usb 2.0即可。另外启用的 USB 端口不要超过15个。

**Comment by sbfkcel** [comment]
> 我的BCM943602CS，睡眠会自动唤醒。我重新定制了USB，内建和外置都不行。网卡的蓝牙我连接在主板的USB转接线，如果不连接就正常，这是什么原因呢？

看样子应该是定制的端口估计错了，先插拔确认下端口号。蓝牙只要 usb 2.0即可。另外启用的 USB 端口不要超过15个。

**Comment by wqianglxf** [comment]
![impicture-333b2023686fa0055985a12cc4bdf20f](https://user-images.githubusercontent.com/66858128/109975537-b2b6df80-7d35-11eb-8d98-255fb79c1146.jpg)
这是我的USB定制，第一项HS02是我BCM蓝牙，内建和USB2，我都 尝试不行，睡眠会自动唤醒

**Comment by wqianglxf** [comment]
https://github.com/sbfkcel/Gigabyte-Z490i-Intel-10700k-5700XT/raw/master/docs/USB.png
还有你用的这个 9pin公对20pin母的USB转接 这个不是主板自带的吧？用这个线，前的USB3.0就没办法用了吧

**Comment by sbfkcel** [comment]
> https://github.com/sbfkcel/Gigabyte-Z490i-Intel-10700k-5700XT/raw/master/docs/USB.png
> 还有你用的这个 9pin公对20pin母的USB转接 这个不是主板自带的吧？用这个线，前的USB3.0就没办法用了吧

不是，淘宝额外购买的。我装的是ITX，通常这个接口在全尺寸机箱上是会自带的。

**Comment by sbfkcel** [comment]
> https://github.com/sbfkcel/Gigabyte-Z490i-Intel-10700k-5700XT/raw/master/docs/USB.png
> 还有你用的这个 9pin公对20pin母的USB转接 这个不是主板自带的吧？用这个线，前的USB3.0就没办法用了吧
你的是什么网卡？型号没有识别出来吗~~~，选中的项是我的
![image](https://user-images.githubusercontent.com/5469785/109986920-26121e80-7d41-11eb-8ce7-2ba6c8141051.png)

**Comment by wqianglxf** [comment]
![image](https://user-images.githubusercontent.com/66858128/110088140-6fa94a80-7dcf-11eb-9cb4-4ecb4243b5d0.png)
我用的是技嘉Z490i自带的那条线，HS02，端口显示的是USB2.0 Hub. 网卡是BCM943602CS三天线![image](https://user-images.githubusercontent.com/66858128/110088455-d890c280-7dcf-11eb-8695-7f0b6253813b.jpeg)
功能上没有问题，就是睡眠会秒醒。

**Comment by sbfkcel** [comment]
自带的线可以插多个接口的吧。试着换个接口看看呢。

**Comment by wqianglxf** [comment]
USB的问题解决了，现在一切都好。期待你的再次更新OC 0.7.0

**Comment by sbfkcel** [comment]
> USB的问题解决了，现在一切都好。期待你的再次更新OC 0.7.0

能用就好了，不着急更新呀。我的显卡出掉了~~~等显卡价格降下来再折腾。
