### ISSUE TITLE
Have you test this with Macos 12.0?

### ISSUE THREAD

**Issue by Zhaoyang-XU** [sbfkcel/Gigabyte-Z490i-Intel-10700k-5700XT#3]
Hi sbfkcel,

我有和你几乎一样的硬件，试过了你的最新的EFI,好像不是很完美，你的都work么？
我不知道你参考这个人的配置没，我之前用的他的，还挺好的。
[ROG z490](https://github.com/xiaovie/Hackintosh-ROG-Z490-series-motherboard-OpenCore)

谢谢，
John

**Comment by sbfkcel** [comment]
有些什么问题呢？

**Comment by Zhaoyang-XU** [comment]
> 

蓝牙/Airdrop 用不了， 休眠也有问题。

**Comment by sbfkcel** [comment]
> 蓝牙/Airdrop 用不了， 休眠也有问题。

我用的是额外购买的MAC网卡，看我列的配置。所以屏蔽了主板内集成的Inter网卡。

相比起MAC原生的网卡，Intel的驱动在速度和兼容上目前都还有很多问题。

休眠问题，确认你是否定制了USB接口。

另外，如果你也跟我使用一样的网卡，蓝牙的USB建议插在主板的USB3.0接口上（见贴图中的9pin公对20pin母的USB转接）。

**Comment by Zhaoyang-XU** [comment]
好的，谢谢。 我也是用的mac的网卡，所以说和你的配置一样。 我用了 20pin的分线器， 订制USB用的2.0，没开3.0口。 如果你的都没问题，那就是我usb订制口的问题。我再好好试一下。

**Comment by Zhaoyang-XU** [comment]
大神，我试了一下，还是不行。直接用的你的usb 订制。蓝牙还是不工作。。。 只改了我的platform info.
还能是其它的原因么？

![Screenshot 2021-12-28 at 02 24 52](https://user-images.githubusercontent.com/13812779/147520900-5c853d52-29f9-42d1-8786-b233fbb6d93b.png)

![Screenshot 2021-12-28 at 02 22 01](https://user-images.githubusercontent.com/13812779/147520851-132f9238-548c-43f9-ade1-b1dd56b2158e.png)

![Screenshot 2021-12-28 at 02 31 39](https://user-images.githubusercontent.com/13812779/147521317-da1cb165-20b3-429f-aedc-06cb2eb03f88.png)

**Comment by Zhaoyang-XU** [comment]
我的12 是从11 升级的，问题是不是可能在这？

**Comment by sbfkcel** [comment]
你的蓝牙是主板上自带的？还是额外购买的MAC网卡？

**Comment by Zhaoyang-XU** [comment]
我用的也是BCM94360cs2 ，所以蓝牙应该也是这上面的。

**Comment by sbfkcel** [comment]
这蓝牙走USB接口的。你先不要定制USB~~~启用那个全部USB的补丁。按里面的注释勾选下方的对应选项。再重启电脑看看
