### ISSUE TITLE
Hi，I tried your efi，but...

### ISSUE THREAD

**Issue by bk210** [sbfkcel/Gigabyte-Z490i-Intel-10700k-5700XT#4]
大佬，我的问题比较繁琐，有劳耐心解答一下（环境：z490i小雕&10850k&12.1正式版镜像&ssd可安装品牌）：
1.我使用你的efi时，没有插显卡直接安装，会卡在第一步的苹果logo，导致无法安装。。。
（我把config_iMac20,2__iGPU display output.plist这个文件改为config.plist之后删除其他plist后安装的）

2.插上6600xt之后，可以安装好系统，但是输入密码进入后没几秒钟就奔溃重启了，并且有macos的自带崩溃提示，自带无线网卡和有线网卡貌似都无法工作。。。还出现了花屏。。。
（原本的config.plist不动，删除其他plist）

我不确定是不是oc版本的问题，也许我用的是0.75的版本，这个和oc版本有关系吗？百忙之中，不吝赐教！

**Comment by sbfkcel** [comment]
跟OC版本没关系。
只需要将对应的plist文件修改为config.plist即可。

你安装的是哪个版本的MACOS呢？

6600建议是12.1以上的MACOS，你的网卡是跟我一样的的型号吗？如果是使用主板自带的无线网卡和蓝牙模块。需要将以下两个驱动加入进去。

https://github.com/OpenIntelWireless/IntelBluetoothFirmware

https://github.com/OpenIntelWireless/itlwm


**加入方法：**

- 打开以上两个项目页面，在右侧的Releases链接中下载对应的kext文件并拷贝到efi下的对应目录中
- 在目录下找到对应的 OpenCore Configurator.app 打开 config.plist 文件，切换到对应的选项卡
- 将上方的两个驱动（kext文件）拖入并保存、再重启即可

**其它问题：**

- 使用主板集显无法安装你需要修改igpu显示的plist文件为config.plist
- 不稳定崩溃的问题，你需要一个个尝试下看尽量少勾选一些驱动看看

**Comment by bk210** [comment]
感谢耐心回复。我用的是12.1正式版本。
网卡目前是自带的，但是考虑购入完全一样的网卡，并使用9pin的转接线，和你的安装保持一致。

另外，我最开始安装的是仅核显的，操作和“使用主板集显无法安装你需要修改igpu显示的plist文件为config.plist”的做法一致，也就是使用igpu display output文件。我看其他朋友也留言有类似的问题，anyway我打算过几天再试一试。

再次感谢回复！

**Comment by sbfkcel** [comment]
好哟。目前主板自带的驱动虽然能用，还是有一些不完美（蓝牙4.0+设备无法使用、隔空投送不能用）。所以我也没有在这里集成

**Comment by bk210** [comment]
大佬，我昨晚又试了一下，用oc7.6的12.1镜像直插6600xt显卡，安装成功了。但是不插显卡用igpu的config文件依然卡在第一部无法进入回复页面。（希望有空也可以帮忙看一下）

再次感谢全面的维护和定制！

**Comment by sbfkcel** [comment]
有独显就不要用核显的了，核显有一些不完美。一些应用有异常现象。

**Comment by bk210** [comment]
好嘞，多谢啦，新年快乐哟！
