### ISSUE TITLE
同样的板子，请问大佬无线网卡是单买cs2 板子还是需要加m2 转接板呢

### ISSUE THREAD

**Issue by hhls** [sbfkcel/Gigabyte-Z490i-Intel-10700k-5700XT#5]

**Comment by hhls** [comment]
后面可否有偿帮忙装机呢

**Comment by sbfkcel** [comment]
加m2的转接板。

装机这活儿不是太方便哟，我不是专业装/卖电脑的。

你要是跟我在同一个城市可以帮忙搞着玩一下（不收费，请喝茶就行）。

**Comment by hhls** [comment]
> 

嗯呐，哈哈哈，都不是问题，我是装完机后，黑果系统想有偿请您远程给装一下，顺带优化下啦

**Comment by hhls** [comment]
> 加m2的转接板。
> 
> 装机这活儿不是太方便哟，我不是专业装/卖电脑的。
> 
> 你要是跟我在同一个城市可以帮忙搞着玩一下（不收费，请喝茶就行）。

非常感谢哈，没时间也没问题哈，到时候找淘宝也行，还是要像大佬学习的 👍
